# Site wide configuration

title:
locale: zh_CN
description: 
logo: site-logo.png
search: true
url: https://fishermartyn.github.io
#url: http://127.0.0.1:4000
#url: http://localhost:4000

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

mathjax: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: fisherMartyn
  avatar: fisher-avatar.png
  email: fisher_thu@foxmail.com
  #disqus-shortname: fisherMartyn
  facebook: fisherMartyn 
  github: fisherMartyn 
  stackexchange: https://stackoverflow.com/users/3959768/fishermartyn
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics: fisherMartyn
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  baidu-siteid: e70a9a72459e5c5fa324d6dbcb738dc2

# enable comments on every page
comments: true

